### ISSUE TITLE
No method error after legitimate move

### ISSUE THREAD

**Issue by benjaminapetersen** [JonathanYiv/chess#1]
Gave the game a shot and unfortunately it exploded right as we got close to a checkmate.

Screenshot of stack trace in terminal:

![screen shot 2017-09-26 at 8 57 07 pm](https://user-images.githubusercontent.com/280512/30890967-232b0c66-a2fe-11e7-8d05-bfdfbaf19a55.jpg)

We had just entered `e6 to e3`, moving the queen forward to take out a pawn and put the king in check.

**Comment by JonathanYiv** [comment]
Looks like I left two conditions out. 
[v1.0.1](https://github.com/JonathanYiv/chess/tree/v1.0.1) patched a fix. 
Thank you.

**Comment by benjaminapetersen** [comment]
What was the fix?

**Comment by JonathanYiv** [comment]
When I enumerate through the nested array that represents the pieces, I first have to check if the piece exists, since some values of the nested array can be 'empty.' There were [two locations](https://github.com/JonathanYiv/chess/commit/ca6dad664eb2866291df2f7c65fea68b3247a33d#diff-f3ca543777bad2bf14b5372abf707395) where I forgot to check it, so it was trying to run methods on nil.
